apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: webapp-deploy
  template:
    metadata:
      labels:
        app: webapp-deploy
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/metrics'
    spec:
      containers:
        - name: webapp-deploy
          image: f18s/kube-news:{{TAG}}
          ports:
            - containerPort: 8080
          env:
            - name: DB_DATABASE
              value: kubenews
            - name: DB_USERNAME
              value: kubenews
            - name: DB_PASSWORD
              value: kubenews
            - name: DB_HOST
              value: postgres
